# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puliapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mapadmin',
        ),
        migrations.AlterField(
            model_name='maplist',
            name='mapAddr',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='maplist',
            name='mapLat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='maplist',
            name='mapLng',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='maplist',
            name='mapName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='maplist',
            name='mapTel',
            field=models.CharField(max_length=20),
        ),
    ]
